version: '3.8'

services:

  sql-db:
    image: postgres:15.2
    container_name: nilfis-sql
    restart: always
    volumes:
      - ./db/sql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./db/sql/sql-tables.sql:/docker-entrypoint-initdb.d/sql-tables.sql
      - ./db/sql/sql-data.sql:/docker-entrypoint-initdb.d/sql-data.sql

    environment:
      - POSTGRES_DB=nilfis
      - POSTGRES_USER=nilfis
      - POSTGRES_PASSWORD=nilfis
    ports:
      - "5432:5432"

  cache-db:
    image: redis:6.2-alpine
    container_name: nilfis-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass nilfis

  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: nilfis-users
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: nilfis
      MONGO_INITDB_DATABASE: app_users
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro